### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by banamon** [sabomate/AR-video_viewer#2]

**Comment by minari515** [comment]
## github actionとの連携ができねぇ

### 出てるエラー
Error: Failed to authenticate, have you run firebase login?

シンプルにログインできてない感じ．
たぶん権限か，認証のための環境変数あたりが悪さしてると予想

**Comment by minari515** [comment]
## 現状の方法

とりあえず環境変数に問題があると仮定して話を進める．．．
今は
```
firebase login:ci
```
というコードを実行した際にコンソールに生成される変数をgithubのsetting->secretに追記してる状態
ただ，[この方法がどうやら古いらしく](https://zenn.dev/sinmetal/articles/firebase-deploy-on-github-actions)，非推奨って言われた．

じゃあほかの方法だよねってことで[ドキュメント](https://github.com/google-github-actions/auth)を読んでみてる

**Comment by minari515** [comment]
ドキュメントがわかりにくくて泣きそうなので，いったんほかの日本語サイトをあさってみてるけど．[こんなのとか](https://note.com/build_service/n/nd4756ceb103f)．

**Comment by minari515** [comment]
OIDC tokenを使ってのも出てくるなぁ．．．何が正しいのか…

**Comment by minari515** [comment]
できたあああ

https://tm-progapp.hatenablog.com/entry/2023/02/05/133737

これみた

**Comment by minari515** [comment]
一応いろいろやったけど，大きく分けると

- IAM APIを有効にする
- サービスアカウントを作成する
- 権限を割り当てる（割り当て過ぎらしいけど今回はオーナーを割り当てた）
- IDを発行する（JSON）
- アカウントIDをコピペする

この辺を行ったらできた．
いつか見返すことがあるかもしれないね

**Comment by tagahei** [comment]
つよつよすぎる！！！
ありがとう！！！
