### ISSUE TITLE
こまごました話し合いのためのいしゅー

### ISSUE THREAD

**Issue by minari515** [sabomate/AR-video_viewer#27]
一応根幹ができてきたので細かい要素とか今後の話し合いをしたい

現状書き出せているissue
- [x]  #6 
- [x] #13 
- [x] #20 
- [ ] #21 
- [x] #25 

これに加えて
- [ ] サムネイルから動画への遷移時，ボタンは再生ボタンでいいのか
- [ ] マーカー画像の選定（たぶん2/16の集合写真）
- [x] 動画サイズの耐久テスト
- [ ] 再生ボタンは再生中はポーズボタンにするか？

ざっとこんな感じかなと

**Comment by minari515** [comment]
すぐに実行できるタスク
- #25 
- サムネイルから動画への遷移時，ボタンは再生ボタンでいいのか
- 動画サイズの耐久テスト

寄せ書きが確定し次第
- #13 

2月16日以降で
- #20 
- #21 
- マーカー画像の選定（たぶん2/16の集合写真）


という感じかなと

**Comment by minari515** [comment]
新たに気づいたことを列挙しまーす

- 動画とサムネイルオブジェクトの大きさの問題
  - 動画のサイズに依存するとおもうけど，小さすぎると認識してるかわからない
  - 大きすぎると，精度が悪い状態での読み取りになってしまって動画が見づらい

> でかいオブジェクトでこちら！みたいに書く→動画は小さくして精度を担保？っていう必要がありそう

- 動画の重さの話
  - #6 にちょっと書いたけど，簡単にfirebaseに動画を置いて，10MB~170MBの4種類を再生してみた
  - 普通に何の問題もなく動画が流れた ．やったぜ
  - ほかのプラットフォームはまだ試してないけどまぁあとででいいかなと

**Comment by minari515** [comment]
https://zenn.dev/fijii_rin/articles/29f046e88adc0b

**Comment by tagahei** [comment]
#46 にまとめた
