### ISSUE TITLE
再生制御をちゃんとしよう

### ISSUE THREAD

**Issue by tagahei** [sabomate/AR-video_viewer#34]
## やること整理
- [x] AR状態，ピン止め状態の制御の管理
- [x] ピン止め状態
  - [x] マーカーロスとしてもUI削除しない
  - [x] ボタン制御で自動再生しない
  - [x] サムネイル表示（確認）
- [x] AR状態
  - [x] markerLost時の制御の確認

**Comment by minari515** [comment]
たしかに！！！！！！！！！！

**Comment by minari515** [comment]
![20240208_131052.jpg](https://github.com/sabomate/AR-video_viewer/assets/126942302/8f6a9517-903b-4327-aa45-281eafc2eccd)

**Comment by minari515** [comment]
ピン状態＋マーカーロストしてもボタンは消さない
どっちかというと

 - ＡＲ状態（マーカーロスト）
 - ＡＲ状態（マーカーファウンド）
 - ピン状態

の三つの状態遷移を持ってる感じ

**Comment by minari515** [comment]
ピン状態の挙動について

- ピン状態では次へ（戻る）ボタンで再生処理は行わない
- 先送りでサムネイルだけ表示する
- 再生ボタンを追加して，再生したらフルスクリーンでの表示（IOSでは勝手になる）

**Comment by tagahei** [comment]
エラー
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22

video.play()は動画コンテンツの非同期読み込みするらしく，その途中で，markerLostして，pause()したときとかに発生する感じっぽい
まぁ，問題はない...がエラーは気になるな

一応対策として，video.play()の引数を受け取って，それが終わっってロードの完了まではpause()しないとかはできるかも

**Comment by tagahei** [comment]
他のエラー
Uncaught (in promise) DOMException: Failed to load because no supported source was found.

たぶんsrcがはいってないってことやんな...
ARモードのmarker発見時の自動再生で出てくるエラーだけど，再現性がないっ！

**Comment by tagahei** [comment]
![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/feab264d-a019-458f-81ec-7c0cd5d607c2)
![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/5d15692a-b3ac-4e8c-bbca-5b5100148600)
