### ISSUE TITLE
動画が重いとFirebaseの無料枠の上限にすぐなる

### ISSUE THREAD

**Issue by tagahei** [sabomate/AR-video_viewer#38]
## Firebaseの上限
1日1GBまでのダウンロードが可能
従量課金制の場合，17円/GBって感じ

|[Croud Storage](https://firebase.google.com/pricing?hl=ja)|
|-|
|![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/3884caf4-a5a7-4a0a-a614-53b508528904)|

## 想定
動画本数：最小20本（M1,B4,B3,卒業生7人)　＋ 個人...？
10人×3回(閲覧) = 30回ダウンロード

1MBの動画の場合，300MBです
田賀の動画見たいな1MBを切るような動画ならワンちゃんあり？

## 対策
- できるだけ軽くする．可能なら1MB以下
- www2に置く（全部で20MBとかなら許され....る？)

**Comment by minari515** [comment]
普通にB4とM2でfirebaseのアカウントを変えるっていうのは思いついた
本質的な解決ではもちろんないけど，選択肢としてあるのは間違いないし単純計算負荷が半分になるならかなり救われることもありそう

**Comment by tagahei** [comment]
かしこぉ

**Comment by tagahei** [comment]
## DownloadされるタイミングはgetDownloadURL()をするときな気がする件

動画を再生せずにページだけ開いた（video/M1の動画に対してgetDownloadURL()を実行)
|Usage|M1のストレージの中身|
|-|-|
|![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/722a3e08-8650-4f55-b015-894a012ab9b4)|![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/f2c4e5f3-1eca-4bd8-af37-9a5c876f40da)|

ほぼ一緒なんだなぁこれが

ってことは，getDownloadURL()を最初にしなければいい

## 解決策候補
プランA：
- 最初に参照のみ配列として取得
- 動画切り替え時にgetDownloadUrlを実行し配列格納
- 一度取得済みの場合はその内容を参照する？
  - getDwonloadUrlで取得したurlにアクセスることがDownloadにカウントされるか不明だから，意味ないのかも...？

プランB：
- getDownloadUrlで取得したUrlって変わるんかな...？
  - もし変わらないなら，直書きとかできたり．．．？

**Comment by tagahei** [comment]
## 一応色々確認
- Refの取得ではダウンロードはしてない（当然か）
- video.playの最初ではダウンロードが発生しているとみられる（結局...?)
- videoの再プレイとかは大丈夫っぽい
- 読み込みじゃなくて，再生をしているのに，動画以上のダウンロードがある．．．？
  - ![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/76d39c7c-3e3e-43f4-bdd9-483fc4e2f697)

-

**Comment by tagahei** [comment]
#43 
Firebase Storage への取得を工夫した

これでだめor不十分だった場合
- www2におく
- 課金する
