### ISSUE TITLE
ロード画面だけつくりたい

### ISSUE THREAD

**Issue by minari515** [sabomate/AR-video_viewer#39]
please, waitingだと少し悲しいので，ARバムめーかーの文字とロゴを表示させたいなと思いました

**Comment by minari515** [comment]
https://web-camp.io/magazine/archives/88516

https://github.com/minari515/Hack-U/blob/master/public%2Fimg%2Fapp_icon.png

Hannotate SC

**Comment by tagahei** [comment]
![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/312a9637-be54-4dd2-a79d-a5bf9f719775)
これ！
