### ISSUE TITLE
マーカーに対してサンブル動画表示

### ISSUE THREAD

**Issue by banamon** [sabomate/AR-video_viewer#4]

**Comment by minari515** [comment]
https://github.com/sabomate/AR-video_viewer/assets/126942302/af9d1410-87bd-462c-83be-d7cac5126445
サンプル画像適当に持ってきて実行

まずは普通の重さ（3MBぐらい）で実行しても真っ黒だったので軽くしてみたバージョン（500KB）も用意

**Comment by minari515** [comment]
全然音沙汰がないので，デプロイ時にパスがおかしくなって参照できてないのかと思った

エラーも確認してみると以下のが出てた

```
components:texture:warn `$s` is not a valid video  ./assets/sample2.mp4
```

**Comment by minari515** [comment]
一応それっぽい回答もみつけた

https://stackoverflow.com/questions/66454292/s-is-not-a-valid-video-depsite-having-png-url

**Comment by minari515** [comment]
ただ，見た感じどうにもならん見たいな書き方してる．．．
パスの指定じゃらちが明かないので一旦URLを指定する感じに変更するます

**Comment by minari515** [comment]
www2のおれのディレクトリ（www2.yoslab.net/~minari/sample/~）に動画を設置してパス指定してみた

![422731554_408788898221028_2755833235980249814_n](https://github.com/sabomate/AR-video_viewer/assets/126942302/5a91061c-3f50-4aae-a38e-4104a69b2c64)

真っ黒が真っ白になったけど，見た感じ何も表示されないのは変わらない

**Comment by minari515** [comment]
F12で確認してみたけど普通にエラーっぽいのは見当たらないかな

音在りの動画で見てみようかなとも考え中

**Comment by minari515** [comment]
<img width="415" alt="image" src="https://github.com/sabomate/AR-video_viewer/assets/126942302/2b204a71-de26-4a62-a62c-1ad399d63703">
あれ，これエラーか？

ちょっと確認してみます

**Comment by tagahei** [comment]
ぶれいぶだからせつ？？

**Comment by minari515** [comment]
いや，普通にhttpからうけとってたからでした

httpsにして試してみます

**Comment by minari515** [comment]
CORSエラー出ました

**Comment by minari515** [comment]
CORSはいつもわからん

**Comment by minari515** [comment]
![421165807_694611442833602_14123931790047357_n](https://github.com/sabomate/AR-video_viewer/assets/126942302/f65a9f7f-d72e-4b89-be92-dbdda614be20)

いけたっぽい…か…？

**Comment by minari515** [comment]
位置調整だけちょっとしましょう
