### ISSUE TITLE
Storageから動画取得して再生

### ISSUE THREAD

**Issue by banamon** [sabomate/AR-video_viewer#5]

**Comment by minari515** [comment]
どうする？これ

普通に全員分の動画×卒業生10人てなるとデータ量は膨大になるから，www2に全部おいていいものか…という思いはある

www3はnginxだから別途調べる必要がある部分もありつつ，storageだとその辺は気にしなくていいかなっていうメリットを感じているところ
storageでいくなら明日（29日 月曜）にでもその辺をやっちゃいたいかなと

**Comment by tagahei** [comment]
WorkChatで話したけど一応残しとく


www2
- メリット
> - もう出来とる簡単
- デメリット
> - 容量不安

www3
- メリット
> - www2みたいに容量そんなに意識しなくていい
- テメリット
> - 将来的に容量がこわい
> - えんじんえっくす？

Storage
- メリット
> - 周りの学生への配慮の容量は意識しなくていい
- デメリット
> - 処理めんどい？一応アルバムメーカーではやっとる
> - 10年後も動くかな

**Comment by minari515** [comment]
# storageでいこう！！！！！！

**Comment by minari515** [comment]
![image](https://github.com/sabomate/AR-video_viewer/assets/126942302/bd7dbcdb-0414-42c0-94bd-4e23a85c49dc)

なんだよこのえらー

**Comment by minari515** [comment]
import関係がなんかうまく行かなかったりもする
```<script type="module"  src="./Reader.js"></script>```
このタイプ指定を行ってインポートで怒られなくなったら次は上に貼ったエラーが出たよ

**Comment by minari515** [comment]
現状共有するぞ

![image](https://github.com/sabomate/AR-video_viewer/assets/126942302/4d7b7184-537e-482d-a326-ffd643456fe6)

これがindex.htmlの発火部分

ここでReader.jsでインポートしてる
<details>

```
import { firebase } from "./firebase/app";
const firebaseConfig = {
  apiKey: "×",
  authDomain: "×",
  projectId: "×",
  storageBucket: "×",
  messagingSenderId: "×",
  appId: "×",
  measurementId: "×"
};
firebase.initializeApp(firebaseConfig);
const storage = firebase.storage();
```

</details>

この二つで動くと思うんだけど全然ダメなのでたすけてほしいのである

**Comment by minari515** [comment]
https://dev.classmethod.jp/articles/lambda-edge-content-type-charset-utf-8/

参考になるかは道だけどエラーで調べて出てくる唯一の日本語記事

**Comment by tagahei** [comment]
サンプル　なんでタイプスクリプトなんじゃろ

https://github.com/firebase/quickstart-js/tree/master/storage

とりあえず，そもそものfirabaseのinportができてない？

**Comment by minari515** [comment]
この機能はなに

**Comment by minari515** [comment]
普通にこめんとかこれ

**Comment by tagahei** [comment]
やったこと
[Firebase を JavaScript プロジェクトに追加する
](https://firebase.google.com/docs/web/setup?hl=ja)の中のステップ2のESM を使用していて、ブラウザ モジュールを使用する場合を参考にした


htmlでやってたことをコメントアウト
```html
    <!-- Firebase JavaScript SDKの追加 -->
    <!-- <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.6.1/firebase-storage.js"></script> -->
```

下記のようにimport
``` firebase.js
import { initializeApp } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-app.js";
import { getStorage } from "https://www.gstatic.com/firebasejs/9.6.1/firebase-storage.js";
```

**Comment by tagahei** [comment]
ブラウザ モジュールは手軽な方法ですが、本番環境ではモジュール バンドルを使用することをおすすめします。

ってかいてあるんよなぁ．．．でも正解が分からんなぁ...

npm install firebaseで入れたfirebaseを参照するのが正解だけど，そうじゃなくて，Web上に用意してあるfirebaseを参照しとるってことだと思うんやけど．．．
どうやってnodeのモジュール入れるんかわからん

**Comment by minari515** [comment]
結構真面目なはなし、フレームワークを使わないバニラJSがひさびさすぎてインポートとかが全然わかってない感じなの辛い

**Comment by minari515** [comment]
こうへいがやったやつをデプロイして実行したら結局CORSエラーが出た．
一応乗り越えられたから何をしたのかメモメモ

実行したのは以下

1．gsutil のインストール

windowsでのpowershellで以下のコマンドを実行
```
(New-Object Net.WebClient).DownloadFile("https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe", "$env:Temp\GoogleCloudSDKInstaller.exe")

& $env:Temp\GoogleCloudSDKInstaller.exe
    
```
この後，わんちゃんログインが発生するかもなのでそれもやる


2．CORS.jsonをプロジェクトのディレクトリ直下に作成

今回は認証のために全部通した
```
[
  {
    "origin": ["*"],
    "method": ["GET"],
    "maxAgeSeconds": 3600
  }
]
```

3．CORS.jsonを配置したディレクトリで以下のコマンドを実行
自身のstorageのURLを取得してきて，そこのアクセスにおけるCORSを認証する感じかなと

```
gsutil cors get gs://************.appspot.com
```
