### ISSUE TITLE
ピン状態の時に動画一覧表示機能の実装

### ISSUE THREAD

**Issue by tagahei** [sabomate/AR-video_viewer#57]
- [x] デザイン考える
- [ ] 実装
  - [ ] 動画の取得方法変更
  - [ ] サムネイル取得
  - [ ] ボタン配置
  - [ ] 一覧ビュー作成

**Comment by tagahei** [comment]
@minari515 適当に書いてみたけどどうおもうすか

一覧ボタン案の一覧

![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/3b8292dc-8a5b-485a-889c-ae82a89eedba)

一覧表示画面案
![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/4e91a942-5189-4e21-92fb-5e069d611990)

**Comment by minari515** [comment]
普通にめっちゃよすぎてすごい

一覧を表示するボタン自体は，俺は普通に四角九つがわかりやすくていいとは思った
