### ISSUE TITLE
重い動画に対応

### ISSUE THREAD

**Issue by banamon** [sabomate/AR-video_viewer#6]
調べる感じ1MB以下がいいという記事がちょいちょいある
一応，3MBぐらいでも動いている動画とかはあった
（動画サイズの目安 1秒0.25MB）

### プランA：動画自体を超軽量化
長くても10秒ぐらいの動画にしてできるだけ解像度を下げて軽くする

### プランB：Gifにする
音声を分けて再生する．タイミング合うかどうかが不安

### プランC：複数動画に分割
数MBの動画に分割して，前の動画が終了したら再生するような処理を記述する

### プランD：分割．．．？
ハックUでFB貰った内容．未知数

**Comment by minari515** [comment]
プランAを軸に進めるしかないような気はしている
現状のシステムでどれくらいの大きさの動画に耐えられるかテストしてみてそれで決めるのもいいかなと思っている

**Comment by minari515** [comment]
どこまでがこのブランチの責務になるかわからんけど，
結局複数の動画を扱うことになるのであれば

- 複数動画の指定方法
　- ランダム？
　- 入力機構？

- 動画再生の方法
　- タップで再生？（画面から動画がFOしたときの処理）
　- 自動再生？GIF？

この辺についての話し合いも必要そう

**Comment by tagahei** [comment]
水木で話すと思うが一応書いとく

- 複数動画を採用するかどうか
  - マーカー凝るのとどっちが優先度が高いか微妙なライン、とりあえず一個でマーカー凝ってから話し合いでもいいかなっておもた
- 入力機構
  - Storageぶち込みでいいと思う！
- 動画再生
  - アルバムメーカーて、認識するとすぐ再生は使いにくいなって思ったけ、個人的にはタップがいいかなっておもた
  - じふかどうかとかは重さ次第かな

**Comment by minari515** [comment]
どのみち全員分のメッセージにするなら絶対複数動画だと思うんだ
だから個人的には

動画＞マーカー

っていう優先度になると思ってるけど，まぁこれは話し合いで決めようか

それいがについては基本的に完全同意なのでそのまま進めます

**Comment by minari515** [comment]
再生サイズ上限を確かめるの忘れてた………

やらねばね

**Comment by minari515** [comment]
動画耐久テストメモ

適当にstorageに動画を4本挙げてみてその再生テストしてみる

20221120_113224_04.mp4：12MB
20221008_124611.mp4：27MB
20231222_122036.mp4：51MB
20230317_204837.mp4：176MB

それぞれの実行した感じをみてみようかなって

**Comment by minari515** [comment]
# 全部何の問題もなく動くわ

ARバムめーかーの苦労は何だったのか

**Comment by tagahei** [comment]
Reactが原因やと思います
