### ISSUE TITLE
IOSフルスクリーンによりピン止め動画が再生できない

### ISSUE THREAD

**Issue by tagahei** [sabomate/AR-video_viewer#73]
できていないこと
- IOSでピン止め動画の再生が最初しかできない

**Comment by tagahei** [comment]
[HTML内で動画を自動再生するためにしたこと](https://qiita.com/Takayuki_Nakano/items/a5faa7bfe57613523c7f)

```
<video autoplay muted playsinline webkit-playsinline src="smpleVideo.mp4"></video>
```

**Comment by minari515** [comment]
一応動いていたころのブランチを触ってみて気づいたこと

- 当時は画面遷移と動画再生が同時だった
- 動画再生さえ始まれば勝手にフルスクリーンになる
- 当時ですらフルスクリーンじゃない状態(ピン状態？)のオブジェクトを触ることは出来なかった

という感じ．
なので目指すべき方向としては
 - ピン状態のオブジェクトを触る手段の確立
 - 二回目以降に自動再生の適応
 - どこかに行ってしまった再生ボタンの復活

多分動画再生差へ始まればフルスクリーンにはなるので，再生ボタンの復活が先決
あとはサムネ表示が死んでるから，もしかしたらサムネは別で持ってくる処理をしてもいいのかも

**Comment by minari515** [comment]
一時停止がないからか！！！
フルスクリーンを経由しないと一時停止状態ってのはあり得なくて，それを今まで認識してなかったからこういうじょうたいになるんだ

**Comment by minari515** [comment]
IOSは動画のcanplayという概念が再生するまで存在しないっぽいから普通にイベントリスナーのcanplayがスルーされとる
これと一時停止が併発してるのが問題っぽいな

**Comment by minari515** [comment]
<img width="603" alt="image" src="https://github.com/sabomate/AR-video_viewer/assets/126942302/a3044442-6282-45b7-b6d8-1dfc17d6d0cb">

全然互換性ありそうなのがなおむかつくな
