### ISSUE TITLE
マーカーをもっといいかんじに

### ISSUE THREAD

**Issue by banamon** [sabomate/AR-video_viewer#8]
### マーカー・ベース
QR コードや特定の画像が黒枠で囲われた専用のマーカーを対象とします
カメラによってマーカーが検出されると，コンテンツを表示します

### イメージ・ベース
NFT (Natural Feature Tracking) ※ Non-Fungible Token ではありません
一定の複雑さを持った画像を対象とします
マーカー・ベースと違い，黒枠で囲わなくても OK
マーカー・ベースよりも処理が重たい

## いいかんじにとは
やっぱり黒枠は目立つ
- プランA：QRコードをマーカとして使用
Viewerを開くためのURLを示すQRコードをそのまま黒枠にして採用．QRコードそのままだと寂しいから，なんかAIのQRとかかわいい感じにしてもいいかも
- プランB：画像をマーカーとしてつかう
  一番理想ではあるが，まだ未知数．

**Comment by minari515** [comment]
正直どこをMVPにするかでだいぶ方針が変わりそうな内容だなという感想

## プランA
普通に何も考えないとこれになると思う．
たとえプランBが採用されたとしても，URLに誘導するためのQRコードに近しい何かは絶対に必要になる．
ただ，黒枠が目立つのは絶対にその通りで，なおかつ寄せ書きともなればさらに目立つなぁと思う

いっそのこと寄せ書きに丸い穴をあけてキーホルダーみたいにマーカーをつけるか
もっと言うともう吉野研アクキーをマーカーにしちゃうとかしてみたいけどこれは関係のない話

なんにせよ目立たない方法＝可読性の低下なのは事実で，これについてはちゃんと方針を練る必要がある

## プランB
プランに分けてコメントしようとしたのにほぼAで書ききってしまった
普通に画像の認識精度に依存するから，時間が許すなら試してみたいとは思うしできることならこっちがいい

ただ未知数なことと，単純に処理が重くなることで全体的に再生できる動画が減る（制限される）のは本末転倒感が否めない
それだったら目立つしダサいけどいい動画が提供されたい

まぁためしてみんとわからんね．

**Comment by tagahei** [comment]
> まぁためしてみんとわからんね

完璧これやな

アクキーとかはおもろいけど納期が早なるのがネック

**Comment by minari515** [comment]
まぁアクキーは夢を語っただけなのでなかったことにしよう

**Comment by tagahei** [comment]
白余白入るっぽいけど，黒縁じゃなくて，色自由に変更で切るっぽい
![image](https://github.com/sabomate/AR-video_viewer/assets/120772851/2306ddd7-e8e8-4f35-b81a-c967eddfb457)

黒縁よりはまぁぎりまぎれれるかも
あとは，寄せ書き全体をマーカーとするのもありっちゃありかなって思た．寄せ書きの淵囲んどいて，寄せ書きを床において遠くから取るとマーカになるとか（寄せ書き正方形縛り）

**Comment by tagahei** [comment]
## Image Tracking
[NFT Marker Creator
](https://carnaux.github.io/NFT-Marker-Creator/#/)でマーカーにしたい画像をアップロードして，画像の特徴点を示すImage Descriptorsを作成する
それをダウンロードして認識するコードでいろいろ書く感じ

サンプルは恐竜の画像から🦖オブジェクト表示
- [Image Tracking Sample Page](https://ar-js-org.github.io/AR.js/aframe/examples/image-tracking/nft/)
- [Image Tracking Sample Image](https://raw.githubusercontent.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex-image-big.jpeg)

参考になりそう
- [AR.js ではじめる Image Tracking
](https://dev.to/ikkou/ar-js-image-tracking-382b)
- [Image Tracking 公式ドキュメント](https://ar-js-org.github.io/AR.js-Docs/image-tracking/)
- [WebARで「Image Tracking」を試してみた
](https://recruit.qukuri.co.jp/blog/xr/webar_imagetracking1/)

**Comment by tagahei** [comment]
#14 
マーカ対応によって画像に対応するようにしました
